version: "3.8"

services:
  # Backend API
  backend:
    build: ./Backend
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb
    networks:
      - otgms-network

  # Frontend (for development/testing with Docker)
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://backend:10000/api
    depends_on:
      - backend
    networks:
      - otgms-network

  # MongoDB (for local development)
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=otgms
    volumes:
      - mongodb_data:/data/db
    networks:
      - otgms-network

volumes:
  mongodb_data:

networks:
  otgms-network:
    driver: bridge
